// Configuração das traduções brasileiras disponíveis na nossa API
export const theVersoesDisponiveis = [
  { id: "acf", nome: "Almeida Corrigida Fiel (ACF)" },
  { id: "ra", nome: "Almeida Revista e Atualizada (RA)" },
  { id: "nvi", nome: "Nova Versão Internacional (NVI)" }
];

// Lista oficial dos 66 livros divididos para nossa engine local e remota
export const todosOsLivrosBatalha = [
  // Antigo Testamento
  { id: "gn", nome: "Gênesis", testamento: "VT", capitulos: 50 },
  { id: "ex", nome: "Êxodo", testamento: "VT", capitulos: 40 },
  { id: "lv", nome: "Levítico", testamento: "VT", capitulos: 27 },
  { id: "nm", nome: "Números", testamento: "VT", capitulos: 36 },
  { id: "dt", nome: "Deuteronômio", testamento: "VT", capitulos: 34 },
  { id: "js", nome: "Josué", testamento: "VT", capitulos: 24 },
  { id: "jz", nome: "Juízes", testamento: "VT", capitulos: 21 },
  { id: "rt", nome: "Rute", testamento: "VT", capitulos: 4 },
  { id: "1sm", nome: "1 Samuel", testamento: "VT", capitulos: 31 },
  { id: "2sm", nome: "2 Samuel", testamento: "VT", capitulos: 24 },
  { id: "1rs", nome: "1 Reis", testamento: "VT", capitulos: 22 },
  { id: "2rs", nome: "2 Reis", testamento: "VT", capitulos: 25 },
  { id: "1cr", nome: "1 Crônicas", testamento: "VT", capitulos: 29 },
  { id: "2cr", nome: "2 Crônicas", testamento: "VT", capitulos: 36 },
  { id: "ed", nome: "Esdras", testamento: "VT", capitulos: 10 },
  { id: "ne", nome: "Neemias", testamento: "VT", capitulos: 13 },
  { id: "et", nome: "Ester", testamento: "VT", capitulos: 10 },
  { id: "job", nome: "Jó", testamento: "VT", capitulos: 42 },
  { id: "sl", nome: "Salmos", testamento: "VT", capitulos: 150 },
  { id: "pv", nome: "Provérbios", testamento: "VT", capitulos: 31 },
  { id: "ec", nome: "Eclesiastes", testamento: "VT", capitulos: 12 },
  { id: "ct", nome: "Cânticos", testamento: "VT", capitulos: 8 },
  { id: "is", nome: "Isaías", testamento: "VT", capitulos: 66 },
  { id: "jr", nome: "Jeremias", testamento: "VT", capitulos: 52 },
  { id: "lm", nome: "Lamentações", testamento: "VT", capitulos: 5 },
  { id: "ez", nome: "Ezequiel", testamento: "VT", capitulos: 48 },
  { id: "dn", nome: "Daniel", testamento: "VT", capitulos: 12 },
  { id: "os", nome: "Oséias", testamento: "VT", capitulos: 14 },
  { id: "jl", nome: "Joel", testamento: "VT", capitulos: 3 },
  { id: "am", nome: "Amós", testamento: "VT", capitulos: 9 },
  { id: "ob", nome: "Obadias", testamento: "VT", capitulos: 1 },
  { id: "jn", nome: "Jonas", testamento: "VT", capitulos: 4 },
  { id: "mq", nome: "Miqueias", testamento: "VT", capitulos: 7 },
  { id: "na", nome: "Naum", testamento: "VT", capitulos: 3 },
  { id: "hc", nome: "Habacuque", testamento: "VT", capitulos: 3 },
  { id: "sf", nome: "Sofonias", testamento: "VT", capitulos: 3 },
  { id: "ag", nome: "Ageu", testamento: "VT", capitulos: 2 },
  { id: "zc", nome: "Zacarias", testamento: "VT", capitulos: 14 },
  { id: "ml", nome: "Malaquias", testamento: "VT", capitulos: 4 },
  
  // Novo Testamento
  { id: "mt", nome: "Mateus", testamento: "NT", capitulos: 28 },
  { id: "mc", nome: "Marcos", testamento: "NT", capitulos: 16 },
  { id: "lc", nome: "Lucas", testamento: "NT", capitulos: 24 },
  { id: "jo", nome: "João", testamento: "NT", capitulos: 21 },
  { id: "at", nome: "Atos", testamento: "NT", capitulos: 28 },
  { id: "rm", nome: "Romanos", testamento: "NT", capitulos: 16 },
  { id: "1co", nome: "1 Coríntios", testamento: "NT", capitulos: 16 },
  { id: "2co", nome: "2 Coríntios", testamento: "NT", capitulos: 13 },
  { id: "gl", nome: "Gálatas", testamento: "NT", capitulos: 6 },
  { id: "ef", nome: "Efésios", testamento: "NT", capitulos: 6 },
  { id: "fp", nome: "Filipenses", testamento: "NT", capitulos: 4 },
  { id: "cl", nome: "Colossenses", testamento: "NT", capitulos: 4 },
  { id: "1ts", nome: "1 Tessalonicenses", testamento: "NT", capitulos: 5 },
  { id: "2ts", nome: "2 Tessalonicenses", testamento: "NT", capitulos: 3 },
  { id: "1tm", nome: "1 Timóteo", testamento: "NT", capitulos: 6 },
  { id: "2tm", nome: "2 Timóteo", testamento: "NT", capitulos: 4 },
  { id: "tt", nome: "Tito", testamento: "NT", capitulos: 3 },
  { id: "fm", nome: "Filemom", testamento: "NT", capitulos: 1 },
  { id: "hb", nome: "Hebreus", testamento: "NT", capitulos: 13 },
  { id: "tg", nome: "Tiago", testamento: "NT", capitulos: 5 },
  { id: "1pe", nome: "1 Pedro", testamento: "NT", capitulos: 5 },
  { id: "2pe", nome: "2 Pedro", testamento: "NT", capitulos: 3 },
  { id: "1jo", nome: "1 João", testamento: "NT", capitulos: 5 },
  { id: "2jo", nome: "2 João", testamento: "NT", capitulos: 1 },
  { id: "3jo", nome: "3 João", testamento: "NT", capitulos: 1 },
  { id: "jd", nome: "Judas", testamento: "NT", capitulos: 1 },
  { id: "ap", nome: "Apocalipse", testamento: "NT", capitulos: 22 }
];